### ISSUE TITLE
Collection migration tracking

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/overview#128]
Instead of always updating [this comment](https://github.com/ansible/community/issues/539#issuecomment-720085434), let's track content moving in this issue. I'll create one comment per collection, and that comment can be updated and eventually checked off or hidden.

When a collection is ready to be added to the current stable release, we have to add it to both ansible.in (just the collection name) and ansible-2.10.build (collection name and version range).  Eventually we'll add code to antsibull to do this.  In the meantime, here's a sample PR that shows what needs to be changed:

https://github.com/ansible-community/ansible-build-data/pull/39/files

**Comment by felixfontein** [comment]
- [x] **community.docker**
  - [x] Repository: https://github.com/ansible-collections/community.docker/
  - [x] Initial release
  - [x] Released 1.0.0
  - [x] Included in Ansible 2.10
  - [ ] Removal announcement PR: https://github.com/ansible-collections/community.general/pull/1303
  - [ ] Removal PR: https://github.com/ansible-collections/community.general/pull/1304

**Comment by felixfontein** [comment]
- [ ] **community.hashi_vault**
  - [ ] Repository
  - [ ] Initial release
  - [ ] Released 1.0.0
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [ ] **community.hrobot**
  - [x] Repository: https://github.com/ansible-collections/community.hrobot
  - [ ] Initial release
  - [ ] Released 1.0.0
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [ ] **community.kubevirt**
  - [x] Repository: https://github.com/ansible-collections/community.kubevirt
  - [ ] Initial release
  - [ ] Released 1.0.0
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [ ] **community.okd**
  - [x] Repository: https://github.com/ansible-collections/community.okd
  - [x] Initial release
  - [x] Released 1.0.0
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR: https://github.com/ansible-collections/community.general/pull/866

**Comment by felixfontein** [comment]
- [x] **community.postgresql**
  - [x] Repository: https://github.com/ansible-collections/community.postgresql/
  - [x] Initial release
  - [x] Released 1.0.0
  - [x] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [x] **community.routeros**
  - [x] Repository: https://github.com/ansible-collections/community.routeros
  - [x] Initial release
  - [x] Released 1.0.0
  - [x] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [ ] **cisco.nso**
  - [x] Repository: https://github.com/CiscoDevNet/ansible-nso
  - [x] Initial release
  - [x] Released 1.0.0
  - [ ] Included in Ansible 2.10: tracking in CiscoDevNet/ansible-nso#4
  - [ ] Removal announcement PR
  - [ ] Removal PR: https://github.com/ansible-collections/community.network/pull/142

**Comment by felixfontein** [comment]
- [ ] **dellemc.openmanage**
  - [x] Repository: https://github.com/dell/dellemc-openmanage-ansible-modules/tree/collections
  - [x] Initial release
  - [x] Released 1.0.0
  - [ ] Included in Ansible 2.10: requires https://github.com/dell/dellemc-openmanage-ansible-modules/pull/174
  - [ ] Removal announcement PR
  - [ ] Removal PR: https://github.com/ansible-collections/community.general/pull/948

**Comment by felixfontein** [comment]
- [ ] **infoblox.nios_modules**
  - [x] Repository: https://github.com/infobloxopen/infoblox-ansible
  - [x] Initial release
  - [x] Released 1.0.0
  - [ ] Included in Ansible 2.10: tracking in infobloxopen/infoblox-ansible#24
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [ ] **kubernetes.core**
  - [x] Repository: https://github.com/ansible-collections/kubernetes.core
  - [x] Initial release
  - [ ] Released 1.0.0 ???
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by felixfontein** [comment]
- [x] **community.google**
  - [x] Repository: https://github.com/ansible-collections/community.google/
  - [ ] Initial release
  - [ ] Released 1.0.0
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR: https://github.com/ansible-collections/community.general/pull/1319

**Comment by felixfontein** [comment]
- [ ] **community.fortios**
  - [ ] Repository
  - [ ] Initial release
  - [ ] Released 1.0.0
  - [ ] Included in Ansible 2.10
  - [ ] Removal announcement PR
  - [ ] Removal PR

**Comment by dericcrago** [comment]
> * community.hashi_vault

Do we want to limit it to _just_ hashicorp vault or should this be something like `community.hashicorp` instead?

**Comment by briantist** [comment]
> > * community.hashi_vault
> 
> Do we want to limit it to _just_ hashicorp vault or should this be something like `community.hashicorp` instead?

@dericcrago We discussed in IRC previously, but I think it should be `hashi_vault`. Other Hashicorp products (consul for example) aren't moving into this collection, so it will be focused on Hashicorp Vault.

**Comment by felixfontein** [comment]
PR to update Ansible's routing table for ansible-core 2.11: https://github.com/ansible/ansible/pull/73046

**Comment by felixfontein** [comment]
Since only infoblox.nios_modules is left, and it's not fully clear how that will progress, I think we can close this.

**Comment by gundalow** [comment]
> Since only infoblox.nios_modules is left, and it's not fully clear how that will progress, I think we can close this.

Agreed we should close.

**Comment by felixfontein** [comment]
infoblox.nios_modules has been added to Ansible, and the migration process has been set into motion (https://github.com/ansible-collections/community.general/pull/3592).
