### ISSUE TITLE
Migration.py limitations and manual steps

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#17]
*THE* place to detail what happens after migrate.py gets run.

If you know of things that I've missed, please ping me, or add comments and I'll update this list.

* Clear out ansible-collection-migration (apart from ansible-base?)
* run migrate.py (FIXME what exact flags)
  * FIXME how do we know it's correct?
   * Store the full log somewhere
* For repos that aren't being moved
  * Archive (which makes them read only)
* If they are being moved, move them

### Part 1
- [x] Move repo or archive if it already exists.
- [ ] Settings app https://github.com/organizations/ansible-collections/settings/installations/5727515
- [x] git checkout -b initial-conf
- [ ] git rm .github/workflows/collection-continuous-integration.yml
-  [ ] Update galaxy.yml
   - [ ] repo +`s` -`migration` ssh->https
   - [ ] Issue link
   - [ ] Comment out dependencies
   - [ ] version 0.1.1
- [ ] Git tag `0.1.0`
- [ ] Publish `0.1.0`

### Part 2
- [ ] Enable Settings GH App
- [ ] PR1
   - [ ] galaxy.yml uncomment dependencies 
   - [ ] settings.yml (to enable branch protections)
   - [ ] Shippable
      - [ ] Enable Shippable https://app.shippable.com/subs/github/ansible-collections/enable
      - [ ] Shippable scripts - executible
      - [ ] shippable.yml
      - [ ] GH Action (Update checkout location x3) inc coverage
   - [ ] GitHub Action
      - [ ] Enable codecod
      - [ ] `.github/workflows/ansible-test.yml`  - Update checkout location
      - [ ] Code coverage
  -  [ ] OPTIONAL: Generate BOTMETA.yml

## Collection Owner
* README.md
* galaxy.yml
* GitHub Owners
* Branch protects
* CI setup
  * Shippable
     * Copy `tests/utils/shippable` from FIXME
     * ~~CodeCov Key~~ Not needed for GitHub action
  * GitHub actions
    * copy `.github/workflows/ansible-test.yml` form FIXME
    * Update checkout location x3
  * Zuul - Who apart from Networking is using this from day one?
* For repos that already exist
  * Diff against generated repo against existing - protection against changes that's gone into devel since the repo was created.
* Generate BOTMETA.yml (for Ansibulbot repos)
* Galaxy Tags?
### Questions
* How do we know where each of the generated GH Repos should move to.
* Which repos should be archived (network, grafana, mongodb, whatelse?)

**Comment by gundalow** [comment]
Migration done, nothing left here
